# Login / Password
maxPasswordLength: 16
minPasswordLength: 6

attempts_to_login: 3

# ONLY 16 CHARACTERS or empty to change it to the default value (It's need to crypt passwords)
key_flag: ""
iv_flag: ""

# Session settings
sessions:
  # Enable/Disable sessions
  enabled: true
  # Stay time (in hours)
  time: 12